FROM node:18.15 AS builder
WORKDIR /build
COPY ./next/ ./
RUN npm ci
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:18
WORKDIR /app
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.6.4 /lambda-adapter /opt/extensions/lambda-adapter
ENV PORT=3000

COPY --from=builder /build/next.config.js ./
COPY --from=builder /build/public ./public
COPY --from=builder /build/.next/static ./.next/static
COPY --from=builder /build/.next/standalone ./

ENTRYPOINT ["node"]
CMD ["server.js"]
